### ISSUE TITLE
Convert this program into a library

### ISSUE THREAD

**Issue by ebm539** [LachlanPaulsen/DSpirolateral#1]

**Comment by EthanJohns02** [comment]
Doesn't sound like an issue. Re-categorize?

**Comment by ebm539** [comment]
> Doesn't sound like an issue. Re-categorize?

Should be labelled an enhancement.

**Comment by LachlanPaulsen** [comment]
File can now be imported. The class tester file is an example of how you can import and use the module. Creating a wheel file is outside the scope of this project. Now get back to work!
